# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-30 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='runwaysDamageData',
            fields=[
                ('damageNo', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='异常')),
                ('runwayType', models.CharField(max_length=2, verbose_name='道面类型')),
                ('damageType', models.CharField(max_length=2, verbose_name='损害类型')),
                ('partitionCode', models.CharField(max_length=10, verbose_name='分区编号')),
                ('Row', models.CharField(max_length=10, verbose_name='板块行编号')),
                ('Col', models.CharField(max_length=10, verbose_name='板块列编号')),
                ('X', models.CharField(max_length=10, verbose_name='X坐标')),
                ('Y', models.CharField(max_length=10, verbose_name='Y坐标')),
                ('location', models.CharField(max_length=50, verbose_name='位置区域')),
                ('damageLength', models.CharField(max_length=10, verbose_name='损害长度')),
                ('damageWidth', models.CharField(max_length=10, verbose_name='损害宽度')),
                ('damageArea', models.CharField(max_length=10, verbose_name='损害面积')),
                ('desc', models.CharField(max_length=200, verbose_name='备注说明')),
                ('damagePic', models.CharField(default='', max_length=500, verbose_name='损害图片地址')),
            ],
            options={
                'verbose_name': '跑滑巡视异常记录',
                'verbose_name_plural': '跑滑巡视异常记录',
            },
        ),
        migrations.CreateModel(
            name='runwaysDamageData_ls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runwayType', models.CharField(max_length=2, verbose_name='道面类型')),
                ('damageType', models.CharField(max_length=2, verbose_name='损害类型')),
                ('partitionCode', models.CharField(max_length=10, verbose_name='分区编号')),
                ('Row', models.CharField(max_length=10, verbose_name='板块行编号')),
                ('Col', models.CharField(max_length=10, verbose_name='板块列编号')),
                ('X', models.CharField(max_length=10, verbose_name='X坐标')),
                ('Y', models.CharField(max_length=10, verbose_name='Y坐标')),
                ('location', models.CharField(max_length=50, verbose_name='位置区域')),
                ('damageLength', models.CharField(max_length=10, verbose_name='损害长度')),
                ('damageWidth', models.CharField(max_length=10, verbose_name='损害宽度')),
                ('damageArea', models.CharField(max_length=10, verbose_name='损害面积')),
                ('desc', models.CharField(max_length=200, verbose_name='备注说明')),
                ('damagePic', models.CharField(default='', max_length=500, verbose_name='损害图片地址')),
            ],
            options={
                'verbose_name': '跑滑巡视异常记临时存放',
                'verbose_name_plural': '跑滑巡视异常记临时存放',
            },
        ),
        migrations.CreateModel(
            name='runwaysPatroData',
            fields=[
                ('taskNo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='任务编号')),
                ('taskType', models.CharField(default='ph', max_length=2, verbose_name='任务类型')),
                ('weather', models.CharField(max_length=100, verbose_name='天气')),
                ('patroDate', models.CharField(max_length=8, verbose_name='巡视日期')),
                ('runways_id', models.CharField(default='', max_length=10, verbose_name='跑道id')),
                ('patroCount', models.CharField(max_length=50, verbose_name='巡视类型')),
                ('patrolReason', models.CharField(default='', max_length=50, verbose_name='巡视原因')),
                ('patroMainCar', models.CharField(max_length=10, verbose_name='巡视主车')),
                ('mainCarPerson', models.CharField(max_length=100, verbose_name='主车人员')),
                ('mainCarDirection', models.CharField(max_length=10, verbose_name='主车方向')),
                ('mainCarTrail', models.CharField(max_length=100, verbose_name='主车巡视轨迹')),
                ('sideCar', models.CharField(max_length=10, verbose_name='巡视副车')),
                ('sideCarPerson', models.CharField(max_length=100, verbose_name='副车人员')),
                ('sideCarDirection', models.CharField(max_length=10, verbose_name='副车方向')),
                ('sideCarTrail', models.CharField(max_length=100, verbose_name='副车巡视轨迹')),
                ('carryGoods', models.CharField(max_length=20, verbose_name='携带物品')),
                ('notifiedTowerTime', models.CharField(max_length=50, verbose_name='通知塔台时间')),
                ('notifiedFlyingTime', models.CharField(max_length=50, verbose_name='通知飞管时间')),
                ('entryTime', models.CharField(max_length=10, verbose_name='进入巡视时间')),
                ('exitWaitingPosition', models.CharField(max_length=10, verbose_name='退出等待位置')),
                ('exitWaitingTime', models.CharField(max_length=50, verbose_name='退出等待时间')),
                ('Re_entryTime', models.CharField(max_length=10, verbose_name='再次进入巡视时间')),
                ('exitNotifiedTowerTime', models.CharField(max_length=50, verbose_name='退出通知塔台时间')),
                ('exitNotifiedFlyingTime', models.CharField(max_length=50, verbose_name='退出通知飞管时间')),
                ('exitTime', models.CharField(max_length=10, verbose_name='结束巡视时间')),
                ('noPatroReason', models.CharField(max_length=200, verbose_name='未巡视原因')),
                ('radioDis', models.CharField(default='', max_length=500, verbose_name='视频地址')),
                ('flag', models.CharField(max_length=1, verbose_name='标志位')),
            ],
            options={
                'verbose_name': '跑滑巡视记录',
                'verbose_name_plural': '跑滑巡视记录',
            },
        ),
        migrations.AddField(
            model_name='runwaysdamagedata',
            name='Patro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runwayPatroManagement.runwaysPatroData', verbose_name='巡视记录'),
        ),
    ]
