# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runwayPatroManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runwaysdamagedata',
            name='damagePic',
            field=models.CharField(default='', max_length=500, verbose_name='损害图片地址'),
        ),
    ]
