# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assessmentItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessmentItem', models.CharField(max_length=5, verbose_name='评估内容')),
                ('assessmentItem1_sureFlag', models.CharField(default='0', max_length=1, verbose_name='评估内容1是否确认标志位')),
                ('Date_1', models.CharField(max_length=10, verbose_name='评估1日期')),
                ('oper_1', models.CharField(max_length=10, verbose_name='评估1记录人')),
                ('assessmentItem2_sureFlag', models.CharField(default='0', max_length=1, verbose_name='评估内容2是否确认标志位')),
                ('Date_2', models.CharField(max_length=10, verbose_name='评估2日期')),
                ('oper_2', models.CharField(max_length=10, verbose_name='评估2记录人')),
                ('suface_Tem_2', models.CharField(max_length=10, verbose_name='评估2地表温度')),
                ('bearingplate_radius_2', models.CharField(max_length=10, verbose_name='评估2承载板半径')),
                ('distance_2', models.CharField(max_length=10, verbose_name='评估2测点间距')),
                ('assessmentItem3_sureFlag', models.CharField(default='0', max_length=1, verbose_name='评估内容3是否确认标志位')),
                ('Date_3', models.CharField(max_length=10, verbose_name='评估3日期')),
                ('oper_3', models.CharField(max_length=10, verbose_name='评估3记录人')),
                ('measuringLine_length_3', models.CharField(max_length=10, verbose_name='评估内容3测线长度')),
                ('samplingDistance_3', models.CharField(max_length=10, verbose_name='评估内容3采样间距')),
                ('testDesc_3', models.CharField(max_length=200, verbose_name='评估内容3测试描述')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AreaTab', verbose_name='区域')),
            ],
            options={
                'verbose_name': '评估条目表',
                'verbose_name_plural': '评估条目表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='damageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=20, verbose_name='单元名称')),
                ('damageType', models.IntegerField(default=0, verbose_name='病害类型')),
                ('damageDegree', models.CharField(max_length=10, verbose_name='病害程度')),
                ('damageNumber', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='病害数量')),
                ('damageUnit', models.CharField(max_length=10, verbose_name='病害单位')),
                ('palteRow', models.CharField(max_length=10, verbose_name='板块行编号')),
                ('palteCol', models.CharField(max_length=10, verbose_name='板块列编号')),
                ('palteX', models.CharField(max_length=10, verbose_name='X坐标')),
                ('palteY', models.CharField(max_length=10, verbose_name='Y坐标')),
                ('diseasephoto', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='病害图片')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AreaTab', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '损坏数据表',
                'verbose_name_plural': '损坏数据表',
            },
        ),
        migrations.CreateModel(
            name='damageData_ls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=20, verbose_name='单元名称')),
                ('damageType', models.IntegerField(default=0, verbose_name='病害类型')),
                ('damageDegree', models.CharField(max_length=10, verbose_name='病害程度')),
                ('damageNumber', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='病害数量')),
                ('damageUnit', models.CharField(max_length=10, verbose_name='病害单位')),
                ('palteRow', models.CharField(max_length=10, verbose_name='板块行编号')),
                ('palteCol', models.CharField(max_length=10, verbose_name='板块列编号')),
                ('palteX', models.CharField(max_length=10, verbose_name='X坐标')),
                ('palteY', models.CharField(max_length=10, verbose_name='Y坐标')),
                ('diseasephoto', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='病害图片')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AreaTab', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '损坏数据临时表',
                'verbose_name_plural': '损坏数据临时表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='deflectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateCode', models.CharField(max_length=20, verbose_name='板编号')),
                ('loadPosition', models.CharField(max_length=20, verbose_name='荷位')),
                ('D1', models.CharField(max_length=20, verbose_name='D1')),
                ('D2', models.CharField(max_length=20, verbose_name='D2')),
                ('D3', models.CharField(max_length=20, verbose_name='D3')),
                ('D4', models.CharField(max_length=20, verbose_name='D4')),
                ('D5', models.CharField(max_length=20, verbose_name='D5')),
                ('D6', models.CharField(max_length=20, verbose_name='D6')),
                ('D7', models.CharField(max_length=20, verbose_name='D7')),
                ('D8', models.CharField(max_length=20, verbose_name='D8')),
                ('D9', models.CharField(max_length=20, verbose_name='D9')),
                ('load', models.CharField(max_length=20, verbose_name='load')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AreaTab', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '弯沉数据',
                'verbose_name_plural': '弯沉数据',
            },
        ),
        migrations.CreateModel(
            name='deflectData_ls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateCode', models.CharField(max_length=20, verbose_name='板编号')),
                ('loadPosition', models.CharField(max_length=20, verbose_name='荷位')),
                ('D1', models.CharField(max_length=20, verbose_name='D1')),
                ('D2', models.CharField(max_length=20, verbose_name='D2')),
                ('D3', models.CharField(max_length=20, verbose_name='D3')),
                ('D4', models.CharField(max_length=20, verbose_name='D4')),
                ('D5', models.CharField(max_length=20, verbose_name='D5')),
                ('D6', models.CharField(max_length=20, verbose_name='D6')),
                ('D7', models.CharField(max_length=20, verbose_name='D7')),
                ('D8', models.CharField(max_length=20, verbose_name='D8')),
                ('D9', models.CharField(max_length=20, verbose_name='D9')),
                ('load', models.CharField(max_length=20, verbose_name='load')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AreaTab', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '损坏数据临时表',
                'verbose_name_plural': '损坏数据临时表',
            },
        ),
        migrations.CreateModel(
            name='join_result_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='脱空均值%')),
                ('level_good', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='好（>80%）')),
                ('level_mid', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='中（56%-80%）')),
                ('level_ci', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='次（31%-56%）')),
                ('level_cha', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='差（<56%）')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AreaTab', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '区域接缝性能评价 数据存放',
                'verbose_name_plural': '区域接缝性能评价 数据存放',
            },
        ),
        migrations.CreateModel(
            name='parameterTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameterType', models.CharField(max_length=10, verbose_name='参数类型')),
                ('parameterCode', models.CharField(max_length=10, verbose_name='参数编号')),
                ('parameterName', models.CharField(max_length=100, verbose_name='参数名称')),
                ('extra', models.CharField(max_length=100, verbose_name='扩展字段_备用')),
            ],
            options={
                'verbose_name': '参数表',
                'verbose_name_plural': '参数表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PCI_result_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaPCI', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='区域PCI')),
                ('areaSCI', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='区域SCI')),
                ('level', models.CharField(max_length=10, verbose_name='评价等级')),
                ('PCI_coefficient', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='PCI变异系数')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AreaTab', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '区域PCI结果存放',
                'verbose_name_plural': '区域PCI结果存放',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='planeness_result_part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineCode', models.CharField(max_length=20, verbose_name='测线名称')),
                ('avg_iri', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='IRI均值')),
                ('cv', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='变异系数')),
                ('level', models.CharField(max_length=20, verbose_name='评价等级')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PartTab', verbose_name='所属部位')),
            ],
            options={
                'verbose_name': '平整度评价 数据存放',
                'verbose_name_plural': '平整度评价 数据存放',
            },
        ),
        migrations.CreateModel(
            name='planenessData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineCode', models.CharField(max_length=20, verbose_name='测线名称')),
                ('stakeNo', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='桩号')),
                ('left_iri', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='左IRI')),
                ('left_variance', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='左方差')),
                ('right_iri', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='右IRI')),
                ('right_variance', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='右方差')),
                ('iri_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='平均iri')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PartTab', verbose_name='所属部位')),
            ],
            options={
                'verbose_name': '平整度数据__临时',
                'verbose_name_plural': '平整度数据__临时',
            },
        ),
        migrations.CreateModel(
            name='planenessData_ls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineCode', models.CharField(max_length=20, verbose_name='测线名称')),
                ('stakeNo', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='桩号')),
                ('left_iri', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='左IRI')),
                ('left_variance', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='左方差')),
                ('right_iri', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='右IRI')),
                ('right_variance', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='右方差')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PartTab', verbose_name='所属部位')),
            ],
            options={
                'verbose_name': '平整度数据__临时',
                'verbose_name_plural': '平整度数据__临时',
            },
        ),
        migrations.CreateModel(
            name='surveyPlan',
            fields=[
                ('surveyPlanCode', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='项目编号')),
                ('year', models.CharField(max_length=4, verbose_name='年度')),
                ('startTime', models.CharField(max_length=10, verbose_name='开始时间')),
                ('endTime', models.CharField(max_length=10, verbose_name='结束时间')),
                ('evaluationUnit', models.CharField(max_length=50, verbose_name='评估单位')),
                ('remark', models.CharField(max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '项目计划表',
                'verbose_name_plural': '项目计划表',
                'ordering': ['surveyPlanCode'],
            },
        ),
        migrations.CreateModel(
            name='void_result_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bian_zhong_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='板边/板中均值')),
                ('bian_zhong_max', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='板边/板中最大值')),
                ('bian_zhong_min', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='板边/板中最小值')),
                ('bian_radio_2_3', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='板边脱空比例（2,3）%')),
                ('bian_radio_3_6', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='板边脱空比例（3.5,6）%')),
                ('jiao_zhong_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='板角/板中均值')),
                ('jiao_zhong_max', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='板角/板中最大值')),
                ('jiao_zhong_min', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='板角/板中最小值')),
                ('jiao_radio_2_3', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='板角脱空比例（2,3）%')),
                ('jiao_radio_3_6', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='板角脱空比例（3.5,6）%')),
                ('radio_2_3', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='总脱空比例（2,3）%')),
                ('radio_3_6', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='总脱空比例（3.5,6）%')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AreaTab', verbose_name='所属区域')),
                ('surveyPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluationManagement.surveyPlan', verbose_name='项目编号')),
            ],
            options={
                'verbose_name': '脱空性能评价 数据存放',
                'verbose_name_plural': '脱空性能评价 数据存放',
            },
        ),
        migrations.AddField(
            model_name='planenessdata_ls',
            name='surveyPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluationManagement.surveyPlan', verbose_name='项目编号'),
        ),
        migrations.AddField(
            model_name='planenessdata',
            name='surveyPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluationManagement.surveyPlan', verbose_name='项目编号'),
        ),
        migrations.AddField(
            model_name='planeness_result_part',
            name='surveyPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluationManagement.surveyPlan', verbose_name='项目编号'),
        ),
        migrations.AddField(
            model_name='pci_result_area',
            name='surveyPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluationManagement.surveyPlan', verbose_name='项目编号'),
        ),
        migrations.AddField(
            model_name='join_result_area',
            name='surveyPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluationManagement.surveyPlan', verbose_name='项目编号'),
        ),
        migrations.AddField(
            model_name='deflectdata_ls',
            name='surveyPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluationManagement.surveyPlan', verbose_name='项目编号'),
        ),
        migrations.AddField(
            model_name='deflectdata',
            name='surveyPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluationManagement.surveyPlan', verbose_name='项目编号'),
        ),
        migrations.AddField(
            model_name='damagedata_ls',
            name='surveyPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluationManagement.surveyPlan', verbose_name='项目编号'),
        ),
        migrations.AddField(
            model_name='damagedata',
            name='surveyPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluationManagement.surveyPlan', verbose_name='项目编号'),
        ),
        migrations.AddField(
            model_name='assessmentitems',
            name='surveyPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluationManagement.surveyPlan', verbose_name='项目编号'),
        ),
    ]
