# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='airport_baseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airportName', models.CharField(max_length=100, verbose_name='机场名称')),
                ('airportCode', models.CharField(max_length=10, verbose_name='机场编码')),
                ('manageInstitution', models.CharField(max_length=100, verbose_name='管理机构')),
                ('airportLevel', models.CharField(max_length=10, verbose_name='机场等级')),
                ('runwayNum', models.IntegerField(verbose_name='跑道数量')),
                ('smoothRoadNum', models.IntegerField(verbose_name='平滑道数量')),
                ('roadSurfaceArea', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='道面面积')),
                ('soilSurfaceArea', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='土面面积')),
                ('seatOfPlaneNum', models.IntegerField(verbose_name='机位数量')),
                ('shippingTime', models.CharField(max_length=50, verbose_name='通航时间')),
                ('recordingTime', models.CharField(max_length=25, verbose_name='记录时间')),
                ('updateTime', models.CharField(max_length=50, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '机场基本信息表',
                'verbose_name_plural': '机场基本信息表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AreaTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaCode', models.CharField(max_length=10, verbose_name='区域编码')),
                ('areaDis', models.CharField(max_length=500, verbose_name='区域位置')),
                ('areaStruct', models.CharField(max_length=50, verbose_name='结构类型')),
                ('structCode', models.CharField(default='', max_length=20, verbose_name='结构组合')),
                ('recordingTime', models.CharField(default='', max_length=25, verbose_name='记录时间')),
                ('updateTime', models.CharField(max_length=50, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '跑道部位信息表',
                'verbose_name_plural': '跑道部位信息表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='cellTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellCode', models.CharField(max_length=10, verbose_name='单元编码')),
                ('recordingTime', models.CharField(max_length=25, verbose_name='记录日期')),
                ('updateTime', models.CharField(default='', max_length=50, verbose_name='更新时间')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AreaTab', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '单元表',
                'verbose_name_plural': '单元表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PartTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partCode', models.CharField(max_length=10, verbose_name='部位编码')),
                ('partName', models.CharField(max_length=50, verbose_name='部位名称')),
                ('partDis', models.CharField(default='', max_length=500, verbose_name='功能描述')),
                ('airCode', models.CharField(default='', max_length=10, verbose_name='机场编号')),
                ('containsAreaNum', models.CharField(default='', max_length=10, verbose_name='包含区域')),
                ('containsStructureNum', models.CharField(default='', max_length=10, verbose_name='包含结构')),
                ('partLevel', models.CharField(default='', max_length=10, verbose_name='重要等级')),
                ('recordingTime', models.CharField(default='', max_length=25, verbose_name='记录时间')),
                ('updateTime', models.CharField(default='', max_length=50, verbose_name='更新时间')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.airport_baseData', verbose_name='所属机场')),
            ],
            options={
                'verbose_name': '跑道部位信息表',
                'verbose_name_plural': '跑道部位信息表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='permissionTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuId', models.CharField(max_length=10, verbose_name='菜单编号')),
                ('menuTitle', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('icon', models.CharField(max_length=10, verbose_name='菜单icon')),
                ('url', models.CharField(max_length=100, verbose_name='菜单url')),
                ('isCurrent', models.CharField(max_length=1, verbose_name='是否默认打开')),
                ('parentmenuId', models.CharField(max_length=10, verbose_name='父级菜单编号')),
                ('level', models.CharField(max_length=10, verbose_name='顺序级别')),
            ],
            options={
                'verbose_name': '权限菜单表',
                'verbose_name_plural': '权限菜单表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='plateTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowNo', models.CharField(max_length=10, verbose_name='行编号')),
                ('colNo', models.CharField(max_length=10, verbose_name='列编号')),
                ('platelength', models.CharField(max_length=10, verbose_name='长度')),
                ('width', models.CharField(max_length=10, verbose_name='宽度')),
                ('area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='面积')),
                ('shape', models.CharField(max_length=50, verbose_name='形状')),
                ('recordingTime', models.CharField(max_length=25, verbose_name='记录日期')),
                ('updateTime', models.CharField(max_length=50, verbose_name='更新时间')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cellTab', verbose_name='所属单元')),
            ],
            options={
                'verbose_name': '板块表',
                'verbose_name_plural': '板块表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='role_permissionTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.permissionTab', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色权限表',
                'verbose_name_plural': '角色权限表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='roleTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=50, verbose_name='角色名称')),
                ('roleDis', models.CharField(max_length=500, verbose_name='角色描述')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='runway_baseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runwayName', models.CharField(max_length=100, verbose_name='跑道名称')),
                ('runwayCode', models.CharField(max_length=10, verbose_name='跑道标志码')),
                ('sizeOfRunway', models.CharField(max_length=10, verbose_name='跑道尺寸')),
                ('sizeOfLiftingBelt', models.CharField(max_length=10, verbose_name='升降带尺寸')),
                ('sizeOfBlastPad', models.CharField(max_length=10, verbose_name='防吹坪尺寸')),
                ('widthOfShoulder', models.CharField(max_length=10, verbose_name='道肩宽度')),
                ('sizeOfSafetyZone', models.CharField(max_length=10, verbose_name='端安全区尺寸')),
                ('operationCategory1', models.CharField(max_length=10, verbose_name='运行类别1')),
                ('operationCategory2', models.CharField(max_length=10, verbose_name='运行类别2')),
                ('takeoffDistance', models.CharField(max_length=10, verbose_name='可用起飞距离')),
                ('takeoffRunDistance', models.CharField(max_length=10, verbose_name='可用起飞滑跑距离')),
                ('runwayFrictionCoefficient', models.CharField(max_length=10, verbose_name='摩擦系数')),
                ('landingDistance', models.CharField(max_length=10, verbose_name='可用着陆距离')),
                ('accelerateStopDistance', models.CharField(max_length=10, verbose_name='可用加速停止距离')),
                ('crossSlope', models.CharField(max_length=10, verbose_name='横坡')),
                ('effectiveLongitudinalSlope', models.CharField(max_length=10, verbose_name='有效纵坡')),
                ('bulletinPCN', models.CharField(max_length=10, verbose_name='通报PCN')),
                ('shippingTime', models.CharField(max_length=50, verbose_name='通航时间')),
                ('recordingTime', models.CharField(max_length=25, verbose_name='记录时间')),
                ('updateTime', models.CharField(max_length=50, verbose_name='更新时间')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.airport_baseData', verbose_name='所属机场')),
            ],
            options={
                'verbose_name': '跑道基本信息表',
                'verbose_name_plural': '跑道基本信息表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structureCode', models.CharField(max_length=10, verbose_name='结构编号')),
                ('layerCode', models.CharField(max_length=10, verbose_name='层次编号')),
                ('materialName', models.CharField(max_length=50, verbose_name='材料名称')),
                ('thickness', models.CharField(max_length=10, verbose_name='厚度')),
                ('elasticModulus', models.CharField(max_length=10, verbose_name='弹性模量')),
                ('CBR', models.CharField(max_length=10, verbose_name='CBR')),
                ('poissonRatio', models.CharField(max_length=10, verbose_name='泊松比')),
                ('recordingTime', models.CharField(max_length=25, verbose_name='记录日期')),
                ('updateTime', models.CharField(max_length=50, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '结构表',
                'verbose_name_plural': '结构表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='structureComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structureClass', models.CharField(max_length=10, verbose_name='类别')),
                ('structureCode', models.CharField(max_length=10, verbose_name='结构编号')),
            ],
            options={
                'verbose_name': '结构组合表',
                'verbose_name_plural': '结构组合表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='user_roleTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.roleTab', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '员工角色表',
                'verbose_name_plural': '员工角色表',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='role_permissiontab',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.roleTab', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='areatab',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PartTab', verbose_name='所属部位'),
        ),
    ]
